### ISSUE TITLE
[INLONG-524] Web API field check logic optimization

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1113]
<p>I planne to optimize the field check of the existing Master’s Web api using the scheme verified on Broker: first, define the field name, and then check it, at the same time, the check function will directly feedback the result.</p>

<p> </p>

<p>It will be divided into multiple sub-issues and proceed step by step according to the class files, we can do it together if you have interest for these tasks.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-524">[INLONG-524]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
