### ISSUE TITLE
[INLONG-564] Adjustment of the project LICENSE and NOTICE

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1153]
<p>Based on the discussion in <span class="error">&#91;1&#93;</span>, we need to sort out the various dependencies of TubeMQ, including the licenses of source code, scripts, binary components, etc.,</p>

<p>For quoted source code or scripts, we plan to directly use the corresponding binary package, or directly replace it with our own solution, to improve the cleanliness of the project license;<br/>
For the referenced binary components, we'll check the LICENSE, and adjust the implementation which the binary packages that do not conform to the apache specification to meet the requirements of the official release.</p>

<p>This task is divided into several sub-tasks for adjustment.</p>

<p>1. <a href="https://lists.apache.org/thread.html/r6858f56cb88ea8a279fb8bbce7be06b2230a701af46d4ac79fc08fee%40%3Cgeneral.incubator.apache.org%3E" class="external-link" rel="nofollow">https://lists.apache.org/thread.html/r6858f56cb88ea8a279fb8bbce7be06b2230a701af46d4ac79fc08fee%40%3Cgeneral.incubator.apache.org%3E</a></p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-564">[INLONG-564]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
