### ISSUE TITLE
[INLONG-767] LICENSE cleanup of third-party dependent packages

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1356]
<p>We need to clean up the LICENSE of third-party dependent packages in accordance with the community's specifications so that it is easy to see which third-party dependent packages do not meet the community version requirements and replace them.</p>

<p>The task may last for multiple versions, and related matters will be divided into subtasks to be processed one by one.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-767">[INLONG-767]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
The  third-party dependent packages LICENSE and NOTICE is traced by https://github.com/apache/incubator-inlong/issues/3422, this issue close.
