### ISSUE TITLE
 Provide management interface SDK

### ISSUE THREAD

**Issue by zhaolei-best** [apache/incubator-inlong#1443]
The http interface provided by tube is too complicated to use, it is best to provide an SDK that encapsulates the original http interface logic

**Comment by gosonzhang** [comment]
@zhaolei-best, well, agree with your point of view. 

This place is really a bit complicated: the master of TubeMQ is a multi-node hot standby mode, and the nodes will be switched at any time during runtime. If the HTTP API can be encapsulated, it will be much more convenient for external programs to call the API.

Let me see how to improve this one

**Comment by gosonzhang** [comment]
This requirement is supported by the HttpUtils.java[1] class, no need to construct SDK
There are programs that need to access TubeMQ's Master server collection through HTTP, you can refer to the demo example and use it directly

[1] inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/HttpUtils.java
