### ISSUE TITLE
Sort Support ClickHouse

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1516]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aloyszhang** [comment]
![image](https://user-images.githubusercontent.com/48062889/132342170-ae96735a-08ca-41ba-b154-e38f7943590a.png)

**Comment by ifndef-SleePy** [comment]
The Sort module has already supported ClickHouse sink. However we have not done any collaboration yet.
