### ISSUE TITLE
[Feature][Sort] Support Iceberg dataflow

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1519]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aloyszhang** [comment]
![image](https://user-images.githubusercontent.com/48062889/132342237-bc2c3eba-2a6e-4b4d-8d9d-8a329a6e1236.png)

**Comment by healchow** [comment]
Supported in #2239 by @chantccc.
