### ISSUE TITLE
Reports ' 'npm run build' failed' error in Windows environment when mvn packages InLong

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#1523]
#### Expected behavior

It is OK in version 0.9.0, but the following error is reported in the windows environment with the master code:

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npm (npm run build) on project inlong-website: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

#### Actual behavior

In cmd, execute "mvn clean package -Dmaven.test.skip=true", the reports error info:
![start](https://user-images.githubusercontent.com/14038849/132087313-a20af759-c00c-49a4-9b13-5f2b9ee28b6b.png)
![mid](https://user-images.githubusercontent.com/14038849/132087320-0337bb7f-9b9d-48a0-a302-bb5000396612.png)
![end](https://user-images.githubusercontent.com/14038849/132087324-c35155c4-a93d-4b79-a21e-898e56080d2e.png)

**Comment by leezng** [comment]
I can't reproduce the problem. It may be a node environment problem, please check your node and npm version.

**Comment by gosonzhang** [comment]
@leezng, it's my environmental problem, thanks!

**Comment by ppyXia** [comment]
windows 
windows git clone code

**Comment by ppyXia** [comment]
https://segmentfault.com/a/1190000021803437

**Comment by ppyXia** [comment]
windows newline symbol is `CRLF`, not the same with linux newline symbol `LR`,
git clone code with property `core.autocrlf=true` will convert `LR` to `CRLF`
1. please  set
`git config --global core.autocrlf false`
and git clone ,then compile code
2. in git bash or wsl bash
`sed -i 's/\r//'  *`

reference：
https://segmentfault.com/a/1190000021803437

**Comment by ppyXia** [comment]
windows newline symbol is CRLF, not the same with linux newline symbol LR,
git clone code with property core.autocrlf=true will convert LR to CRLF

please set
git config --global core.autocrlf false
and git clone ,then recompile code
in git bash or wsl bash
sed -i 's/\r//' *
reference：
https://segmentfault.com/a/1190000021803437

**Comment by thesumery** [comment]
> windows newline symbol is CRLF, not the same with linux newline symbol LR, git clone code with property core.autocrlf=true will convert LR to CRLF
> 
> please set git config --global core.autocrlf false and git clone ,then recompile code in git bash or wsl bash sed -i 's/\r//' * reference： https://segmentfault.com/a/1190000021803437

new discussion: https://github.com/apache/inlong/discussions/4459

**Comment by ly100120** [comment]
I 've encountered the same problem. Could you show more details about this ? I still have no idea how to handle it.兄弟，这个问题主要是什么？能否详细说一下？万分感谢
