### ISSUE TITLE
GoSDK should throw error if it fail to connect to master.

### ISSUE THREAD

**Issue by TszKitLo40** [apache/incubator-inlong#1527]
#### Expected behavior

Tell us what should happen
GoSDK should throw error if it fail to connect to master.
#### Actual behavior
GoSDK does not throw error if it fail to connect to master.
Tell us what happens instead

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**InLong version**: 0.11.0

**Comment by gosonzhang** [comment]
3 questions:
1. Not start the server and only start the client, the client does not check whether the registration is successful and then go to the next status;
2. Started the server, the client does not respond to the registration event of the master after registering the master;
3. The client did not re-register the Master after the Master restarted
