### ISSUE TITLE
Java SDK should deal with the default flow control rule

### ISSUE THREAD

**Issue by TszKitLo40** [apache/incubator-inlong#1552]
#### Expected behavior

Tell us what should happen
Java SDK should deal with the default flow control rule
#### Actual behavior

Tell us what happens instead
Java SDK doesnot deal with the default flow control rule
![Java SDK](https://user-images.githubusercontent.com/18443139/133190785-168b2d9c-9d40-4454-83f8-18897598432f.png)

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**InLong version**: 0.11.0

**Comment by gosonzhang** [comment]
@TszKitLo40, thanks, let me check it
