### ISSUE TITLE
C++ SDK can not return error code of PartInUse and PartWaiting correctly

### ISSUE THREAD

**Issue by TszKitLo40** [apache/incubator-inlong#1560]
#### Expected behavior

Tell us what should happen
If the index partitions are empty and the used partitions are empty, `err_code::kErrAllPartWaiting` should be returned.
If the index partitions are empty and the used partitions are not empty, `err_code::kErrAllPartWaiting` should be returned.
#### Actual behavior

Tell us what happens instead
<img width="796" alt="wecom-temp-db47e9e13bbff3eb6f69ceb3c4073d32" src="https://user-images.githubusercontent.com/18443139/133373766-14da0c41-6c9f-4473-a751-956fca363040.png">

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**InLong version**: 0.11.0

**Comment by gosonzhang** [comment]
Ok, I get it, thanks @TszKitLo40
