### ISSUE TITLE
InLong's website does not work without Javascript

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#1581]
According to the requirements of the Apache project, the official website of the project cannot have Javascript[1]. The operation of the current InLong official website relies on Javascript, if the operation of Javascript is blocked, the page display will be abnormal, and the current official website needs to be adjusted without Javascript.

1. https://lists.apache.org/thread.html/re4af6faa37fb9f71644dddf385e97b8accaa46439f73aa57665f9df2%40%3Cgeneral.incubator.apache.org%3E

**Comment by dockerzhang** [comment]
this PR #1631 has refactored the office website by Docusaurus.
