### ISSUE TITLE
[Feature] Introduce flink to dataproxy module

### ISSUE THREAD

**Issue by ghost** [apache/incubator-inlong#1599]
## Description

Apache inlong contains four module, includes Ingest, Converge, Cache, Consume. After looking into the project, we
can find that there is a similar structure in several modules, we can call it "source - channel - sink"(SCS in short). 
- Ingest module, there is a customized "source - channel - sink" structure. 
- DataProxy module, we can see this module depends on flume project, which is a typical SCS structure.
- Consume module, we can also think flink is also a SCS structure.

Several disadvantages:
In Ingest module, we may need to implement many sources ourselves, inculdes streaming and batch ingest, like cdc, file, socket...
In DataProxy module, as we known, the development of flume project is getting slower.

We can see that it's hard for us to maintain them, we need to learn the flume api and implements many connectors. The apache flink already contains rich connectors, and support sql grammar, batch and streaming source connectors, also 
contains many other excellent features, we can benefit from it. So, here we can merge some functions of the Ingest, Converge module and introduce flink to dataproxy module.

## Architecture 
Here the new architecture diagram compared to origin.

### Origin
![image](https://user-images.githubusercontent.com/91316485/136642894-d7a7fd5c-45a7-46b3-ba72-00066839a176.png)

### New
![image](https://user-images.githubusercontent.com/91316485/136642903-89730b52-6b46-4a57-8791-890c72d2327c.png)

**Comment by dockerzhang** [comment]
@leo65535 @gosonzhang Thank you for the great thinking of InLong. I try to understand this question from another side.
we agree that `apache flink` has rich and mature connectors,  maybe we could add a plugin implement like **DataProxy on Flink** in the future. But at present, we will keep the flume implement for DataProxy, and will not replace it with Flink in the recent versions for some reasons:
1, InLong has an internal version that serving lots of Tencent businesses for years, we found that there are no MQ services that could process the super-large scale data, that why we add DataProxy(using flume) and develop TubeMQ.
2, we will focus on adding more data flow for the following versions,  like ClickHouse、IceBerg、HBase, and DataProxy support Pulsar, we will not replace it with Flink immediately.

**Comment by leo65535** [comment]
Hi @dockerzhang @gosonzhang 

> But at present, we will keep the flume implement for DataProxy, and will not replace it with Flink in the recent versions

+1, you are right.

> maybe we could add a plugin implement like DataProxy on Flink in the future.

Yeah, this is what I want to talk about, not to replace flume right now.

**Comment by gosonzhang** [comment]
The issue has not been dealt with for a long time, so I closed it first
