### ISSUE TITLE
[Improve] TubeMQ Documents should use English pictures 

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1655]
### Description

All TubeMQ Documents should use English pictures.

1,  [TubeMQ architecture](https://inlong.apache.org/docs/modules/tubemq/architecture)
![image](https://user-images.githubusercontent.com/18047329/137424727-ed390246-65c3-426a-822f-22874aa3a0cf.png)

2，[quick start](https://inlong.apache.org/en-us/docs/modules/tubemq/quick_start.html)
![image](https://user-images.githubusercontent.com/18047329/137424797-82ff5cd3-c36e-475b-b358-69538152164d.png)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@gosonzhang PTAL, thanks.

**Comment by gosonzhang** [comment]
Picture 1, I think it can be modified; Picture 2, because the console is only in Chinese, it is more difficult to adjust
