### ISSUE TITLE
[Improve][translation] the guide of how-to-release should be translated into English

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1660]
### Description

the guide of [how-to-release](https://inlong.apache.org/development/how-to-release) should be translated into English

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aloyszhang** [comment]
@jinze1107 
Hi, are you still want to work on this issue?
