### ISSUE TITLE
[Improve][translation] the guide of how-to-verify should be translated into English

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1661]
### Description

the guide of [how-to-verify](https://inlong.apache.org/development/how-to-verify) should be translated into English

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@jinze1107, are you still working on this issue? If not, I'll do it, thanks!
