### ISSUE TITLE
[feature] website support process pulsar dataflow 

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1711]
### Description

website support process pulsar data access

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leezng** [comment]
[ ] #1834 
[ ] #1835 
[ ] #1836 
[ ] #1837
