### ISSUE TITLE
[Feature][agent] Add agent metric statistics

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1712]
### Description

Add Agent metric statistics

https://inlong.apache.org/docs/next/modules/agent/overview#monitor-metrics-configuration

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@shink, can you claim this issue? so that I can assign it to you

**Comment by shink** [comment]
@gosonzhang Yes, I can.
