### ISSUE TITLE
[Feature][dataproxy] Add dataproxy metric statistics

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1713]
### Description

Add dataproxy metric statistics

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shink** [comment]
Does this issue need to be handled like #1866 ?

**Comment by dockerzhang** [comment]
fixed by https://github.com/apache/incubator-inlong/pull/2057, so close it.
