### ISSUE TITLE
[Bug] [DataProxy] Build data proxy module failed when not skip tests

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#1724]
### What happened

When i execute the build command:

```shell
mvn clean install --settings my-settings.xml
```

there are some error occured:

![image](https://user-images.githubusercontent.com/31994335/139519125-535aac8e-3b23-49fa-8f6d-fcdbc56d27f6.png)

### What you expected to happen

The build should be successful here, and there should be no errors.

### How to reproduce

In master branch, just execute following command:

```shell
mvn clean install --settings my-settings.xml
```

### Environment

macOS Monterey 12.0.1

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
due to not happening again, close it.
