### ISSUE TITLE
[Bug]TubeMQ HTTP API download link cannot be opened

### ISSUE THREAD

**Issue by leno1001** [apache/incubator-inlong#1745]
### Description

获取HTTP API文档的链接打不开
问题地址：https://inlong.apache.org/zh-CN/docs/modules/tubemq/appendixfiles/http_access_api_definition_cn.xls
![image](https://user-images.githubusercontent.com/31943616/140271078-d16d50be-2cac-4663-9c97-61da231daae8.png)

### InLong Component

InLong Website

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@leno1001 thanks! wait a minute

**Comment by dockerzhang** [comment]
@leno1001  this issue is fixed by https://github.com/apache/incubator-inlong-website/pull/173, it will close.
