### ISSUE TITLE
[Bug] Website readme error

### ISSUE THREAD

**Issue by leezng** [apache/incubator-inlong#1771]
### What happened

![image](https://user-images.githubusercontent.com/13777294/140848134-635fb375-66c0-4217-9368-40bb16dc9408.png)

### What you expected to happen

Change to InLong

### How to reproduce

README.md

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Thanks @leezng
