### ISSUE TITLE
[Bug] Get error while parse td msg with go client

### ISSUE THREAD

**Issue by hawickhuang** [apache/incubator-inlong#1776]
### What happened

When call 
`
for _, msg := range cr.Messages {
      log.Infof("msg id: %d, topic: %s", msg.ID, msg.Topic)
      if err != nil {
	      log.Errorf("failed to parse td msg: %v", err)
	      time.Sleep(1 * time.Second)
	      break
      }
}
`

I got: 

code: 11, msg:parse message error:  snappy uncompressed v4's compress's length failure

### What you expected to happen

no error

### How to reproduce

msg.Data: 

### Environment

Linux

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@hawickhuang, thanks, this question has been merged by https://github.com/apache/incubator-inlong/issues/1777
