### ISSUE TITLE
[Bug] Get uncorrect time value of attributes

### ISSUE THREAD

**Issue by hawickhuang** [apache/incubator-inlong#1781]
### What happened

get attributes like:   

map[jbid: xxxxxx cnt: 1 dt:56407224 msgUUID:f38e3e98-4fe9-4f42-85a0-c412b075d1 tid: xxxxxxxx],

### What you expected to happen

the value of dt should be like: 1630485910; 

### How to reproduce

for {
	time.Sleep(10 * time.Second)
	cr, _ := cli.GetMessage()
	if err != nil {
		log.Errorf("failed to get message: %v", err)
		time.Sleep(1 * time.Second)
		continue
	}
        for _, msg := range cr.Messages {
		log.Infof("msg id: %d, topic: %s", msg.ID, msg.Topic)
		m, err := tdmsg.New(msg.Data)
		log.Debug("m: ", spew.Sdump(m.IsNumBid), spew.Sdump(m.CreateTime), spew.Sdump(m.Version),
			spew.Sdump(m.AttrCount), spew.Sdump(m.MsgCount))
		if err != nil {
			log.Errorf("failed to parse td msg: %v", err)
			time.Sleep(1 * time.Second)
			break
		}
                ....
}

### Environment

linux

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@hawickhuang, thanks!

**Comment by TszKitLo40** [comment]
@hawickhuang Thanks, I will fix it.
