### ISSUE TITLE
[Bug] Topic filters config has't any effects

### ISSUE THREAD

**Issue by hawickhuang** [apache/incubator-inlong#1783]
### What happened

i have config filters in address, but util receive other message of this topic 
      
```
  addr := fmt.Sprintf(
		"%s?topic=%s&group=%s&filters=%s",
		host,
		topic,
		group,
		filters,
	)
	cfg, err := tubeconfig.ParseAddress(addr)
```

### What you expected to happen

just get the message in config

### How to reproduce

```
addr := fmt.Sprintf(
		"%s?topic=%s&group=%s&filters=%s",
		host,
		topic,
		group,
		filters,
	)
	log.Debug(addr)

	cfg, err := tubeconfig.ParseAddress(addr)
```

### Environment

linux

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TszKitLo40** [comment]
Thanks, I will fix it.
