### ISSUE TITLE
[Improve] update the architecture for office-website

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1810]
### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@bluewang, can you claim this issue? so that I can assign it to you

**Comment by gosonzhang** [comment]
@bluewang, can you claim this issue? so that I can assign it to you
