### ISSUE TITLE
 [INLONG-811] Sort Module Support store data to Elasticsearch

### ISSUE THREAD

**Issue by huzk8** [apache/incubator-inlong#1823]
### Description
InLong only support store data to Clickhouse now, it's better to support Elasticsearch.
JIRA link - [INLONG-811](https://issues.apache.org/jira/projects/INLONG/issues/INLONG-811?filter=allopenissues) 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@huzk8 we have planned the Elasticsearch feature, it will be released in the next versions. And it is very welcome if you are pleased to contribute to this feature.

By the way, all issues have migrated from the Jira, you can only create an issue at the GitHub Issues next time.

**Comment by healchow** [comment]
In addition, InLong currently supports storing data in Hive, and the feature of storing in ClickHouse is under development.

**Comment by huzk8** [comment]
I am interested in writing the doc about how to store data to clickhouse.



发自我的iPhone


------------------ Original ------------------
From: healchow ***@***.***&gt;
Date: Mon,Nov 22,2021 8:24 PM
To: apache/incubator-inlong ***@***.***&gt;
Cc: huzk ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/incubator-inlong]  [INLONG-811] Sort Module Support store data to Elasticsearch (Issue #1823)






In addition, InLong currently supports storing data in Hive, and the feature of storing in ClickHouse is under development.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dockerzhang** [comment]
duplicate with https://github.com/apache/incubator-inlong/issues/4236
