### ISSUE TITLE
[Feature] Add official website content search button

### ISSUE THREAD

**Issue by bluewang** [apache/incubator-inlong#1831]
### Description

the official website link is: http://inlong.apache.org/

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Chever-John** [comment]
Hi, may I use `algolia` to finish this issue?

**Comment by bluewang** [comment]
of course. use this： DocSearch: Search made for documentation | DocSearch
by Algolia <https://docsearch.algolia.com/> ？

John Chever ***@***.***> 于2022年4月27日周三 21:28写道：

**Comment by Chever-John** [comment]
@bluewang OK, Please assign it to me. I want to try~

**Comment by dockerzhang** [comment]
@Chever-John thanks. 
the office website project is at
https://github.com/apache/incubator-inlong-website/

we can refer to https://skywalking.apache.org/
![image](https://user-images.githubusercontent.com/18047329/165668629-a2b1806b-2a51-4ca7-acb0-bea1469710dd.png)

**Comment by dockerzhang** [comment]
@Chever-John do you still work on this issue?

**Comment by Chever-John** [comment]
This task is in progress.
Sorry for the delay in this task!
