### ISSUE TITLE
[Improve] Supplement deployment document

### ISSUE THREAD

**Issue by Kathy110** [apache/incubator-inlong#1839]
### Description

The broker component can't run well in my computer environment only if the parameter in the configuration file _broker.ini_ is added:
`defEthName=ens33`
I think it better to add this point into the official deployment document.

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@Kathy110 do you have a plan to fix this issue?
