### ISSUE TITLE
[Bug][Manager] Adding columns to a Hive table does not take effect

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#1858]
### What happened

1. Add column named `name` for Hive storage.

![image](https://user-images.githubusercontent.com/31994335/143835425-916440e1-e693-42e1-a260-a8eaf122d801.png)

2. The workflow was executed successfully.

![image](https://user-images.githubusercontent.com/31994335/143835709-9898bd68-d12d-4d72-a979-769f81475ef1.png)

3. But there is no such field in the Hive table.

![image](https://user-images.githubusercontent.com/31994335/143836052-e0b2350d-3ae4-4c4a-82e9-2388d4fb50c3.png)

### What you expected to happen

The system can successfully add fields to the Hive table.

### How to reproduce

1. Apply for a business, which includes a data stream and Hive storage, add a field named `id`.

2. Passed the approval and the Hive table is successfully created.

3. Modify the Hive storage, just add any field, save.

4. Make sure the workflow was successful.

![image](https://user-images.githubusercontent.com/31994335/143836793-1edbf75d-f014-48a3-b86d-b7c847753529.png)

5. Go to the Hive table and check that the field you just added is not actually added.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
The problem may be here: `inlong-manager/manager-service` -> `HiveTableOperator#createHiveTable` method.

**Comment by woofyzhao** [comment]
Verifying.

**Comment by woofyzhao** [comment]
Fixed by invoking stream operation on update.
