### ISSUE TITLE
[Improve][TubeMQ]  repHelperHost for master should be exposed in configuration

### ISSUE THREAD

**Issue by aloyszhang** [apache/incubator-inlong#1863]
### Description

Currently, `repHelperHost` in master.ini isn't exposed. 
See https://github.com/apache/incubator-inlong/blob/master/inlong-tubemq/conf/master.ini?#L70

This is a key configuration for Tube master especially when you build a failover master service.

So, it should be exposed, also, we should add some guides for this configuration

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@aloyszhang, you are right, the parameters of the copy are very important, and each copy group requires a different parameter configuration; commenting it out will make the outside mistakenly think that only the default value is needed.

**Comment by gosonzhang** [comment]
Can you contribute a PR?

**Comment by aloyszhang** [comment]
Yeah, I'll send a pull request soon.
