### ISSUE TITLE
[Improve] There are several errors in TubeMQ's guidance document

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#1865]
### Description

Q1: 
https://inlong.apache.org/zh-CN/docs/modules/tubemq/quick_start#151-%E9%85%8D%E7%BD%AEbroker%E5%85%83%E6%95%B0%E6%8D%AE
Two guidance pictures in this part are duplicated.

Q2: 《TubeMQ HTTP API》looks like a link?
https://inlong.apache.org/zh-CN/docs/modules/tubemq/quick_start#3-%E7%BB%93%E6%9D%9F

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
I'll process the first question

The second question, is a document, because the form is more complicated, and MD can not handle it, so it is directly provided in the form of a document

Thanks @bruceneenhl
