### ISSUE TITLE
[Improve][InLong-Common] Improve JMX and Prometheus monitor interface

### ISSUE THREAD

**Issue by shink** [apache/incubator-inlong#1875]
### Description

We can abstract an interface so that we can use the same interface with different monitor implementations.

For example.

```java
public abstract class AbstractSourceStatManager {

    // metric
    protected CounterMetric successCount;

    public void incrSuccessCount() {
        successCount.incr();
    }
}
```

After `SourceJmxStatManager` and `SourcePrometheusStatManager` implement it, we can use the same interface with different implementations in `DatabaseSource`.

```java
public class DatabaseSource {

    private final AbstractSourceStatManager statManager;

    public MySource() {
        statManager = new SourceJmxStatManager();
    }

    public MySource(AbstractSourceStatManager statManager) {
        this.statManager = statManager;
    }

    public void split() {
        // do something
        // increment metric
        statManager.incrSuccessCount();
    }
}
```

```java
// prometheus.enable=false
DatabaseSource source = new DatabaseSource();
// prometheus.enable=true
DatabaseSource source = new DatabaseSource(new SourcePrometheusStatManager(...));

source.split();
```

### InLong Component

InLong Common

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@shink, the idea should be no problem, why close this issue?

**Comment by gosonzhang** [comment]
@shink, ok, I get it

By the way, does this PR need to be incorporated into version 0.12.0? I see that it is still in an error state but has not been processed

**Comment by shink** [comment]
@gosonzhang Yeah. I have found the reason for the error, and I will complete it tonight.

**Comment by gosonzhang** [comment]
Ok,
