### ISSUE TITLE
inlong Audit

### ISSUE THREAD

**Issue by baomingyu** [apache/incubator-inlong#1883]
### Description

Inlong audit will handle all metrics info which reported by client sdk in separate processing .
This is the master issue for inlong audit feature, including the following sub-tasks.

- [ ] 1.  #1879
- [ ] 2.  #1880
- [ ] 3.  #1881
- [ ] 4.  #1882

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
This issue is duplicated with https://github.com/apache/incubator-inlong/issues/1738, close this issue
