### ISSUE TITLE
[Feature]Inlong-Sort-Standalone support JMX metrics listener for pushing.

### ISSUE THREAD

**Issue by luchunliang** [apache/incubator-inlong#1894]
### Description

Inlong-Sort-Standalone support JMX metrics listener for pushing.

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
fixed by #1930 ,close it
