### ISSUE TITLE
[Bug][Doc] Page not found when Business configuration was hit in the website: docs/user_guide module

### ISSUE THREAD

**Issue by Fisher666** [apache/incubator-inlong#1912]
### What happened

Page Not Found : doc of Business configuration part unavailable 
![image](https://user-images.githubusercontent.com/45913164/144783061-2c0f5d5b-1687-47f7-8521-0c8efe51629a.png)

### What you expected to happen

Most likely, it'd be an erroneous behavior of url jump.

### How to reproduce

1. hit this:   https://inlong.apache.org/docs/user_guide/quick_start

2. choose 0.11.0
![image](https://user-images.githubusercontent.com/45913164/144782419-e4159f05-cc8f-4a36-b57b-5f698d6e0a47.png)

3. follow the following steps : 
![image](https://user-images.githubusercontent.com/45913164/144782690-fb1086a8-9b14-4cd8-b7ed-b1bbbad42bd7.png)

4. you'd see the abnormal page:
![image](https://user-images.githubusercontent.com/45913164/144782757-1bea6ee6-b074-4779-9b71-afc4e2916209.png)

### Environment

Google chrome :Version 92.0.4515.159 (Official Build) (x86_64) 
InLong version : v0.11.0 

postscript： v0.11.0 is not choosable in below InLong version part.

### InLong version

0.10.0 RC1

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
fixed in the `next` version.

![企业微信截图_1638761897387](https://user-images.githubusercontent.com/18047329/144784179-32c6e98a-56b4-4ea3-b6d6-df5b0190c8e4.png)
