### ISSUE TITLE
[Bug] TubeMQ HTTP API xls can not download

### ISSUE THREAD

**Issue by leezng** [apache/incubator-inlong#1919]
### What happened

TubeMQ HTTP API xls can not download

### What you expected to happen

success

### How to reproduce

TubeMQ HTTP API xls can not download

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Thanks @leezng
