### ISSUE TITLE
Failed to start up MultiSession factory by following the demo code [Bug]

### ISSUE THREAD

**Issue by dashuye4** [apache/incubator-inlong#1920]
### What happened

I was unable to startup the multiSession factory by following the demo code
<img width="884" alt="wecom-temp-81c13709de04c4cbdf3465e476410f10" src="https://user-images.githubusercontent.com/8169163/144997517-0db741c8-55e9-4107-bb1d-e0bf2c334577.png">
By telling me that, the worker had been shutdown raising from Netty channel closed.
I wander if two multisession factory instance share the same Netty channel or some problems on object synchronized result in this problem.
thanks.

### What you expected to happen

demo code should run correctly.

### How to reproduce

start another consumer process with multisession factory interface, when there exists one on running.

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@dashuye4, great!!

This possibility does exist in this place, thank you very much!

By the way, can you help us with a PR for modification? You had found this problem, I believe you must have thought about how to modify it.

**Comment by gosonzhang** [comment]
@dashuye4, thanks for your contribution!!
