### ISSUE TITLE
Release InLong 0.12.0

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#1941]
### Description

This is the master issue for releasing InLong 0.12.0, including the following sub-tasks:

- [x] #1943
- [x] #1944 
- [x] #1945 
- [x] #1946 
- [x] #1947 
- [x] #1948 
- [x] #2062

**Comment by dockerzhang** [comment]
all 0.12.0 has been pushed.
https://registry.hub.docker.com/r/inlong/

![image](https://user-images.githubusercontent.com/18047329/147524965-04eb7f61-6abc-4543-9517-cba8a41738a5.png)

**Comment by gosonzhang** [comment]
The release tasks have been completed,  so the issue is closed
