### ISSUE TITLE
[Feature] DataProxy sdk add demo 

### ISSUE THREAD

**Issue by baomingyu** [apache/incubator-inlong#1949]
### Description

[Feature] DataProxy sdk add demo 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
Duplicated with #2215, close it.
