### ISSUE TITLE
[Bug]inlong-sort does not support pulsar ???

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#1954]
### What happened

when I start an inlong-sort application:  
`./flink run -c org.apache.inlong.sort.flink.Entrance /data/apache-inlong/apache-inlong-incubating/inlong-sort/sort-core-0.12.0-incubating-SNAPSHOT.jar --cluster-id inlong_app \
        --zookeeper.quorum xx.xx.xx.xx:2181 --zookeeper.path.root /inlong-sort --source.type pulsar --sink.type hive -d &`
error occurs like this picture:

![sort-error](https://user-images.githubusercontent.com/67505181/145401602-61deb2ef-4e61-4c7a-b992-115e1a87d356.png)

### What you expected to happen

successfully starting a inlong-sort application with pulsar source-type

### How to reproduce

start an inlong-sort application with pulsar source-type

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ifndef-SleePy** [comment]
Hi @bruceneenhl , thanks for feeding back. The sort module does not open the entry for Pulsar yet. I will fix it asap.

**Comment by ifndef-SleePy** [comment]
@dockerzhang could you assign this ticket to me?

**Comment by ifndef-SleePy** [comment]
Fixed via https://github.com/apache/incubator-inlong/pull/1961.
