### ISSUE TITLE
[Bug]Source data fields' type are all mapped to tinyint, and can not be modified

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#1955]
### What happened

create hive storage, the type of the data fields which are synchronized from source data field are all mapped to tinyint, and can not be modified
![map-wrong](https://user-images.githubusercontent.com/67505181/145403630-fd9fcc30-dda5-4e8f-8293-cbefffafbb9a.png)

### What you expected to happen

I except the type to be  same with source data fields'.

### How to reproduce

set one or more source data field, and create hive or other storage 

### InLong version

master

### InLong Component

InLong Website

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@leezng, can you claim this issue? so that I can assign it to you

**Comment by leezng** [comment]
I have fixed it in #1963

**Comment by gosonzhang** [comment]
Thanks
