### ISSUE TITLE
[Bug][InLong-Manager] Cannot create the Pulsar subscription

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#1967]
### What happened

create pulsar subscription error
![订阅失败](https://user-images.githubusercontent.com/67505181/145809272-faf10f1d-9ee4-4106-8c5c-fe2268fb3d48.png)

### What you expected to happen

the pulsar subscription can be created rightly

### How to reproduce

create a data access using pulsar

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@ciscozhou, can you claim this issue? so that I can assign it to you

**Comment by ciscozhou** [comment]
OK, I will deal with this issue.
