### ISSUE TITLE
[Bug]with the demo conf of dataproxy, the app can not start rightly

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#1973]
### What happened

with the demo conf of dataproxy, the app can not start rightly

### What you expected to happen

please just give a right conf example

### How to reproduce

with the demo conf of dataproxy to start app

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baomingyu** [comment]
ok, i will fix it.
