### ISSUE TITLE
[Bug]the content of topics.properties generated incorrectly，and too much backup files generate automatically 

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#1980]
### What happened

inlong groupId instead of null will be in the left side of "="(as p1)，and dataproxy generates too much junk files in a short period of time(as p2), it's not easy to clear after a long time.
p1:
![p1](https://user-images.githubusercontent.com/67505181/145953190-0313b534-1f47-420d-a4eb-7df2fc637389.png)
p2:
![p2](https://user-images.githubusercontent.com/67505181/145953468-3bd7d9a1-2b70-439e-aef3-76ab4fbd680e.png)

### What you expected to happen

topics.properties be generated correctly
Reduce the number of backup files

### How to reproduce

create data access and start dataproxy app

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EMsnap** [comment]
leave it to me?
