### ISSUE TITLE
[Bug] When compiling the project, the InLong-audit module reported Warning errors

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#1981]
### What happened

"mvn compile", a view like this:

![image](https://user-images.githubusercontent.com/14038849/145953961-3dc78870-050a-4fd6-bce1-1948b945046a.png)

### What you expected to happen

no warning information

### How to reproduce

"mvn compile"

### Environment

windows

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baomingyu** [comment]
ok, i will fix it

**Comment by gosonzhang** [comment]
ok, thanks
