### ISSUE TITLE
[Bug]some font of " DataProxy-SDK architecture " page  incorrectly

### ISSUE THREAD

**Issue by xupt-sdp** [apache/incubator-inlong#1989]
### What happened

look at this 
![image](https://user-images.githubusercontent.com/49757367/145996713-d7e504b5-218f-46b2-a15e-1ece4c0d68e7.png)

### What you expected to happen

some font is wrong.

### How to reproduce

open this website:https://inlong.apache.org/zh-CN/docs/modules/dataproxy-sdk/architecture/

### Environment

standard Chrome

### InLong version

master

### InLong Component

InLong DataProxy-SDK

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EMsnap** [comment]
pls fix it thx, remove the 送 character

**Comment by EMsnap** [comment]
@xupt-sdp

**Comment by xupt-sdp** [comment]
@EMsnap it's my pleasure.I'll submit a pr.

**Comment by xupt-sdp** [comment]
@EMsnap should i add the bug in “incubator-inlong-website” and fix?I'm a green hand

**Comment by dockerzhang** [comment]
@xupt-sdp you can start a PR for [incubator-inlong-website](https://github.com/apache/incubator-inlong-website) refer to [how-to-commit](https://inlong.apache.org/development/how-to-commit).

**Comment by baomingyu** [comment]
overview has change in this pr
https://github.com/apache/incubator-inlong-website/pull/271
