### ISSUE TITLE
[Feature]sort-flink support to get configuration from inlong-manager

### ISSUE THREAD

**Issue by luchunliang** [apache/incubator-inlong#1991]
### Description

sort-flink support to get configuration from inlong-manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
the latest implementation is that inlong-manager creates a sort Flink job with configuration needed, close it.
