### ISSUE TITLE
[Bug] Compile Audit-SDK and report TestNGException

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#1995]
### What happened

When I use "mvn clean package install" to compile the project, I find that the Audit-SDK module reports TestNGException, 

For details, see:

[audit-sdk.error.txt](https://github.com/apache/incubator-inlong/files/7716183/audit-sdk.error.txt)

### What you expected to happen

no exception report

### How to reproduce

use "mvn clean package install" to compile the project

### Environment

windows

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by doleyzi** [comment]
I fix it

**Comment by gosonzhang** [comment]
ok, @doleyzi
