### ISSUE TITLE
[Bug]after the compilation of inlong, no lib directory in inlong-dataproxy

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#1997]
### What happened

use " mvn clean install -DskipTests " to compile inlong, no lib directory in inlong-dataproxy

### What you expected to happen

lib dir in dataproxy

### How to reproduce

compile inlong

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baomingyu** [comment]
ok, i will fix it
