### ISSUE TITLE
[Feature]creating data access with pulsar, users should be able to change the ensemble param 

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#2002]
### Description

creating data access with pulsar, users should be able to change the ensemble param 

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leezng** [comment]
See #2008
