### ISSUE TITLE
[Bug]inlong-dataproxy could not identify the groupId and topic format of topics.properties

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#2014]
### What happened

inlong-dataproxy could not identify the groupId and topic format of topics.properties
the format like this: b_test_pulsar_hive/test_data_stream=persistent://public/b_test_pulsar_hive/test_data_stream

### What you expected to happen

none

### How to reproduce

create a pulsar data access

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baomingyu** [comment]
ok i will fix it.
