### ISSUE TITLE
[Bug]the message of  inlong-agent sent is not filled with streamId

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#2024]
### What happened

create a pulsar data access. the message of  inlong-agent sent is not filled with streamId

### What you expected to happen

format of message be right

### How to reproduce

create a pulsar data access. the message of  inlong-agent sent is not filled with streamId

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@bruceneenhl, is the issue a duplicate of https://github.com/apache/incubator-inlong/issues/2023?

**Comment by gosonzhang** [comment]
I'll close this issue
