### ISSUE TITLE
[Bug]inlong-agent raises NPE error when running 

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#2030]
### What happened

inlong-agent raises NPE error when running 
![agent-NPE-error](https://user-images.githubusercontent.com/67505181/146723627-c6b5d7d3-8841-4f2f-b0ae-900af5f75ec8.png)

### What you expected to happen

none

### How to reproduce

create a data access with a file data source

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EMsnap** [comment]
leave it to me pls
