### ISSUE TITLE
[Bug]inlong-sort abandon data from pulsar due to an ClassCastException

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#2038]
### What happened

create a  pulsar data access, inlong-sort abandon data from pulsar
as shown p1 and p2：
p1:
![p1](https://user-images.githubusercontent.com/67505181/146737499-41e6e878-caf7-4627-8846-50f1fb9b8b0d.png)
p2:
![p2](https://user-images.githubusercontent.com/67505181/146737522-418e4bbf-8464-4ffe-acba-830611d42da8.png)

### What you expected to happen

none

### How to reproduce

create a pulsar data access, and start a inlong-sort job, finally insert some test data

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chantccc** [comment]
please assign to me
