### ISSUE TITLE
[Bug]inlong-sort could not identify tube master address when inlong-sort and tube-master were deployed in the same machine

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#2046]
### What happened

inlong-sort could not identify tube master address when inlong-sort and tube-master were deployed in the same machine
![tube-master-address-error](https://user-images.githubusercontent.com/67505181/146920084-a6617f8f-9435-451c-8bca-e37dc6f4cde7.png)

### What you expected to happen

none

### How to reproduce

create a tube data access, and insert some test data

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@bruceneenhl, I got it, thanks!
