### ISSUE TITLE
[Feature] [InLong audit] Audit Web Page Display

### ISSUE THREAD

**Issue by doleyzi** [apache/incubator-inlong#2053]
### Description

This is a sub issue for releasing InLong audit of Web Page Display.
![image](https://user-images.githubusercontent.com/43397300/147029120-407d1f17-1434-4ef4-a38e-7c48df7f8b67.png)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
fixed by https://github.com/apache/incubator-inlong/pull/2222
