### ISSUE TITLE
[Improve][InLong Website] The InLong Logo can be put in the inlong-website login page

### ISSUE THREAD

**Issue by leezng** [apache/incubator-inlong#2060]
### Description

![image](https://user-images.githubusercontent.com/13777294/147336996-1404993f-ee77-4c4a-b8fc-de1f737e683b.png)

The InLong Logo can be put in the inlong-website login page. It may be a universal design.

### InLong Component

InLong Website

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunnyjain15699** [comment]
Hi, I would like to work on this issue. Can you guide me through it ?

**Comment by leezng** [comment]
First, you can replace title with logo.

**Comment by Sanket-777** [comment]
is this issue still open

**Comment by dockerzhang** [comment]
@Sanket-777 yes, do you plan to fix it?

**Comment by Sanket-777** [comment]
> @Sanket-777 yes, do you plan to fix it?

Yes ,i wanna make a try

**Comment by dockerzhang** [comment]
@Sanket-777 this issue was assigned to you, please fix it recently, thanks a lot.
