### ISSUE TITLE
Add 0.12.0 release document

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#2062]
### Description

Add 0.12.0 release document in InLong website

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bluewang** [comment]
I will handle this task

**Comment by gosonzhang** [comment]
@bluewang ok
