### ISSUE TITLE
[Question] inlong-website module and incubator-inlong-website repo

### ISSUE THREAD

**Issue by tisonkun** [apache/incubator-inlong#2081]
### Question

Do we use both of them for building our website? It seems that https://github.com/apache/incubator-inlong-website is the one actually used. If so, we can remove inlong-webiste module as unused.

cc @gosonzhang 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@tisonkun, well, this place is really easy to confuse people, what words to use or how to organize it better?

https://github.com/apache/incubator-inlong-website is the address of our official website content, inlong-website is just the front-end page code of inlong-Manager, we tried to put it inside the inlong-Manager module, but found Compiling under windows does not pass.

**Comment by tisonkun** [comment]
Thanks for your explanation! Either move to inlong-manager or name it as inlong-dashboard looks good to me. It's definitely not a "site".

**Comment by dockerzhang** [comment]
@tisonkun Great idea. Could you create a new feature issue?

**Comment by dockerzhang** [comment]
'inlong-website' is replaced by `inlong-dashboard`.
see the detail:
https://github.com/apache/incubator-inlong/pull/2197
