### ISSUE TITLE
[Bug]A bug in the Go SDK demo, and the API result class is not clear enough

### ISSUE THREAD

**Issue by rjm521** [apache/incubator-inlong#2084]
### Description

After communicating with the author, the problem is this:
Using the latest master version of TubeMQ's Go SDK, running according to the Demo, it was found that there was no expected data consumption print log, and the offset of the server was continuously confirmed.

After a relatively long period of time, it is found that the following problems are caused, it is recommended that InLong improve this one to prevent others from having the same problem and being tossed, thanks!

This is question snapshot:
https://github.com/apache/incubator-inlong/blob/master/inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/multi_routine_consumer.go#L79:
![image](https://user-images.githubusercontent.com/14038849/147807172-2884db3a-0c67-4fcb-a9b2-dd4ed7cf5c66.png)

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@rjm521, thanks!

**Comment by dockerzhang** [comment]
@rjm521 please add a title for this issue.
