### ISSUE TITLE
[Bug] Miss a "-p" flag before 2181:2181 in the command "Start Standalone Container"

### ISSUE THREAD

**Issue by rjm521** [apache/incubator-inlong#2087]
### Description

One `-p` flag missing before `2181:2181` in the command of _Start Standalone Container_.

https://github.com/apache/incubator-inlong/blob/master/inlong-tubemq/tubemq-docker/tubemq-all/README.md
![image](https://user-images.githubusercontent.com/14038849/147807388-d3ab2e78-7cc0-41e6-bb57-3c8f089e6b12.png)

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@rjm521, thank you!!!

By the way, I see that you have already pointed out this problem. would you like to contribute a PR to us for modification?

**Comment by gosonzhang** [comment]
I'll do it, or it will be 1 year
