### ISSUE TITLE
[Feature][agent] support db collect

### ISSUE THREAD

**Issue by justinwwhuang** [apache/incubator-inlong#2111]
### Description

support to fetch db collect task 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
close it for https://github.com/apache/incubator-inlong/pull/2110
