### ISSUE TITLE
[Bug] version 0.12.0 cannot pass UT

### ISSUE THREAD

**Issue by justinwwhuang** [apache/incubator-inlong#2137]
### What happened

 at org.apache.inlong.dataproxy.metrics.TestDataProxyMetricItemSet.testResult(TestDataProxyMetricItemSet.java:168)
![image](https://user-images.githubusercontent.com/26856549/148941954-40357495-f21b-4de6-85b3-8e418c6cbdea.png)

### What you expected to happen

UT should be passed

### How to reproduce

down load and build with mvn package
https://github.com/apache/incubator-inlong/releases/tag/0.12.0-incubating-RC0

### InLong version

0.12.0

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@luchunliang PTAL
