### ISSUE TITLE
[Feature][agent] support db SQL collect

### ISSUE THREAD

**Issue by EMsnap** [apache/incubator-inlong#2141]
### Description

[agent] support db SQL collect
support sql collect through submitting job locally

### Use case

[agent] support db SQL collect
support sql collect through submitting job locally

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
Completed by https://github.com/apache/incubator-inlong/pull/2168, so close it.
