### ISSUE TITLE
Make MySQL an optional dependency of InLong-TubeMQ-Manager

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#2284]
### Description

The parent issue is: https://github.com/apache/incubator-inlong/issues/2281

Based on the parent requirements, according to the requirements of ASF 3RD PARTY LICENSE POLICY, we need to replace them or change the current non-standard third-party mandatory dependencies into non-mandatory dependencies. The InLong-TubeMQ-manager module is forced to rely on MySQL, which needs to be adjusted.

This issue tracks modification handling in this regard.

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
duplicated with https://github.com/apache/incubator-inlong/issues/2784, close it.
