### ISSUE TITLE
[Feature][Manager] Put inlong group id in dataflow info for Sort

### ISSUE THREAD

**Issue by chantccc** [apache/incubator-inlong#2286]
### Description

Sort will use inlong group id for reporting metrics, so manager should put this in the dataflowInfo.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chantccc** [comment]
please put inlong group id in the map

**Comment by healchow** [comment]
Solved by https://github.com/apache/incubator-inlong/pull/3052
