### ISSUE TITLE
[Feature][Manager] Add Cluster Management for MQ/DataProxy/Sort Cluster

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#2305]
### Description

 Add Cluster Management for MQ/DataProxy/Sort Cluster, and we could get the status of all modules quickly.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Supported in #3945 and #3967.
