### ISSUE TITLE
[WIP] Apache InLong Users Register

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#2316]
### Description

If you are using Apache InLong, you are very welcome to submit a comment on this issue, the comment includes:

- Organization Name:
- Location:
- Contact Email:
- Usage Scenario:

e.g:
- Organization Name: Tencent Cloud
- Location: Shenzhen, China
- Contact Email: dockerzhang@tencent.com
- Usage Scenario: massive data integration

**Comment by luchunliang** [comment]
Organization Name: Tencent PCG
Location: Shenzhen, China
Contact Email: rudylu@tencent.com
Usage Scenario: ATTA data integration

**Comment by shink** [comment]
- Organization Name: (for personal use)
- Location: Xi'an, Shaanxi, China
- Contact Email: jiyuanhao@stu.xidian.edu.cn
- Usage Scenario: learning, developing and contributing

**Comment by yunqingmoswu** [comment]
Organization Name: Tencent Cloud
Location: Shenzhen, China
Contact Email: [yunqingmo@tencent.com](mailto:yunqingmo@tencent.com)
Usage Scenario: massive data integration

**Comment by dockerzhang** [comment]
duplicated with https://github.com/apache/incubator-inlong/discussions/3846
