### ISSUE TITLE
[Feature] Support PB compression protocol format of proxy sdk and cache message, based on Protobuffer protocol

### ISSUE THREAD

**Issue by luchunliang** [apache/incubator-inlong#2375]
## Description

Support new protocol format of proxy sdk and cache message, based on Protobuffer protocol.
New protocol will replace TDMsg protocol. It will be more general.

## Child issue:
- [ ] 1. #2376
- [ ] 2. #2377
- [ ] 3. #2378
- [ ] 4. #2379
- [ ] 5. #2380
- [ ] 6. #2381
- [ ] 7. #2382
- [ ] 8. #2383
- [ ] 9. #2384
- [ ] 10. #2385
- [ ] 11. #2386

### Proxy SDK protocol
Type: TCP
Protocol: PB

#### Main format of request
<html>
<body>

Parameter | Length | Remark
-- | -- | --
totalLength | 4 | The total length of body parameter and the length of version parameter(2).
version | 2 | Protocol version, for the different PB protocol.The first value is 0x0001.
body | totalLength | main data, PB protocol.PB class: MessagePack

</body>
</html>

#### PB protocol of body parameter (version:1) of request

syntax = "proto2";

package org.apache.inlong.sdk.commons.protocol;

enum INLONG_COMPRESSED_TYPE
{
  INLONG_NO_COMPRESS = 0;
  INLONG_GZ = 1;
  INLONG_SNAPPY = 2;
};

message MapFieldEntry {
  optional string key = 1;
  optional string value = 2;
}

message MessagePackHeader {
  required string inlongGroupId = 1;  //inlongGroupId 
  required string inlongStreamId = 2;  //inlongStreamId 
  required int64 packTime = 3; //pack time, milliseconds
  required int32 msgCount = 4;	//message count
  required int32 srcLength = 5;	//total length of raw messages body
  required int32 compressLen = 6;	//compress length of messages
  required INLONG_COMPRESSED_TYPE compressType = 7;  //compress type
  repeated MapFieldEntry params = 8;     //additional parameters
}

message MessageObj {
  required int64 msgTime = 1; //message generation time, milliseconds
  required string sourceIp = 2; // agent ip of message generation
  required bytes body = 3; //message body
  repeated MapFieldEntry params = 4;	//additional parameters
}

message MessageObjs {
  repeated MessageObj msgs = 1;      //message list
}

message MessagePack {
  required MessagePackHeader header = 1;  //message pack header
  required bytes compressBytes = 2;     //compressed bytes of MessageObjs serialization bytes, or MessageObjs serialization bytes(compressType=INLONG_NO_COMPRESS)
}

#### Main format of response
<html>
<body>

Parameter | Length | Remark
-- | -- | --
totalLength | 4 | The total length of body parameter and the length of version parameter(2).
version | 2 | Protocol version, for the different PB protocol.The first value is 0x0001.
body | totalLength | main data, PB protocol.PB class: ResponseInfo

</body>
</html>

#### PB protocol of body parameter (version:1) of response
syntax = "proto2"; 
package org.apache.inlong.sdk.commons.protocol;

enum ResultCode{
  SUCCUSS = 0,				// success
  FAIL = -1,				// general error code
  ERR_VERSION_ERROR = -101,	// not support version
  ERR_LENGTH_ERROR = -102,	// error length, the length is negitive or over.
  ERR_REJECT = -103,        // Proxy rejects the request, because proxy can not process more data, or the cache cluster can not be connected.
  ERR_PACKAGE_ERROR = -104,	// request data can not be decoded with PB protocol.
  ERR_ID_ERROR = -105		// inlongGroupId or inlongStreamId is bad; The length is wrong, or the CRC check is wrong.
}

message ResponseInfo {
  ResultCode result = 1;	//response result
}

#### Message format
<html>
<body>

Parameter | Type | Remark
-- | -- | --
headers | Map<String,String> | version=1
body | byte[] | compressed bytes of MessageObjs serialization bytes,or MessageObjs serialization bytes(compressType=INLONG_NO_COMPRESS)

</body>
</html>

#### Headers format
<html>
<body>

Parameter | Type | Remark
-- | -- | --
version | int32 | protocol version, the value is 1
inlongGroupId | string | inlongGroupId
inlongStreamId | string | inlongStreamId
proxyName | string | proxy node id, IP or conainer name
packTime | int64 | pack time, milliseconds
msgCount | int32 | message count
srcLength | int32 | total length of raw messages body
compressType | int | compress type of body dataINLONG_NO_COMPRESS = 0,INLONG_GZ = 1,INLONG_SNAPPY = 2
messageKey | string | partition hash key, optional

</body>
</html>

#### Body Format (PB protocol)
syntax = "proto2";

package org.apache.inlong.sdk.commons.protocol;

message MapFieldEntry {
  optional string key = 1;
  optional string value = 2;
}

message MessageObj {
  required int64 msgTime = 1; //message generation time, milliseconds
  required string sourceIp = 2; // agent ip of message generation
  required bytes body = 3; //message body
  repeated MapFieldEntry params = 4;	//additional parameters
}

message MessageObjs {
  repeated MessageObj msgs = 1;      //message list
}

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@luchunliang Please add more detail for the `new protocol format`, what problems it plans to solve, and it's better to add a specific name for this protocol.
