### ISSUE TITLE
[Bug] upgrade elasticsearch client jar due to cves

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-inlong#2425]
### What happened

https://discuss.elastic.co/c/announcements/security-announcements/31

Not sure if all these issues relate just to elasticsearch server side - still feels like client jar should be upgraded just in case

Dependabot id recommending upgrade to at least the latest v6 jar - 6.8.23

### What you expected to happen

n/a

### How to reproduce

n/a

### InLong version

master

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@pjfanning thanks for your contributions to security issues recently.
Do you know some tools or plugins which can scan all potential security issues for InLong? After that, we can add an [action workflow](https://github.com/apache/incubator-inlong/actions)  for future PRs, make it found before committing.

**Comment by pjfanning** [comment]
@dockerzhang I'm using dependabot - I'm not sure if you can add it to this project directly but in your github fork, you can go to the 'Security' tab and enable 'Dependabot alerts'. Within a few moments, you will see the same list of jar and npm issues I see in my fork.

**Comment by dockerzhang** [comment]
@pjfanning thanks. `'Dependabot alerts` maybe is only available for person repo, and there is `CodeQL Analysis` for the InLong project, i will add it later.
![image](https://user-images.githubusercontent.com/18047329/153171480-11cfde8e-4f84-416d-b086-12dde85c39a2.png)
