### ISSUE TITLE
[Bug]standalone deploy script need to update

### ISSUE THREAD

**Issue by gong** [apache/incubator-inlong#2429]
### What happened

Hi, the directory which is generated by packaging is different with scripts. For example, can't find `inlong-manager-web`

### What you expected to happen

The script executes correctly

### How to reproduce

mvn clean install -DskipTests
you can find directory ,as shown below
<img width="801" alt="file" src="https://user-images.githubusercontent.com/9883232/153192966-f85cd2cf-b753-44b3-ac17-98a7149456a5.png">
you can't find `inlong-manager-web`, and you find it in inlong-daemon.sh and init-config.sh
> https://github.com/apache/incubator-inlong/blob/master/bin/inlong-daemon.sh
> https://github.com/apache/incubator-inlong/blob/master/bin/init-config.sh

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by crancchen** [comment]
i will fix at next version
