### ISSUE TITLE
[Improve] upgrade hadoop dependency

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-inlong#2450]
### Description

The existing hadoop version that inlong builds with has CVEs - published security vulnerabilities. Would it be possible to upgrade to hadoop 2.10.1 if hadoop 3.x is too big a leap?

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@chantccc PTAL this issue, thanks.

**Comment by Kodalien** [comment]
@dockerzhang  assign to me
