### ISSUE TITLE
[Bug] a number of CVEs exist for NPMs exist in dashboard

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-inlong#2461]
### What happened

I did a dependabot analysis of InLong and have submitted maven fixes but I'm not a UI specialist so haven't attempted to update the NPM modules.

Some of the highest severity issues include (there are many more):
* https://github.com/advisories/GHSA-33f9-j839-rf8h
* https://github.com/advisories/GHSA-hxcc-f52p-wc94
* https://github.com/advisories/GHSA-ww39-953v-wcq6

`npm audit` and `npm audit fix` can be used

### What you expected to happen

n/a

### How to reproduce

n/a

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@leezng PTAL, thanks.

**Comment by gosonzhang** [comment]
@pjfanning, thanks, you are professional!

**Comment by leezng** [comment]
@pjfanning 
I try to use `npm audit fix` to resolve some vulnerabilities. But there are still some that involve breaking changes. Because they are lower-level dependencies of development dependencies, theoretically they will not affect the UI layer.
