### ISSUE TITLE
[Bug] is aviator LGPL licensed jar ok to include in an ASF product?

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-inlong#2464]
### What happened

Aviator jar is LGPL licensed [2] - used in InLong Agent. 

I'm no expert of open source licenses and I know GPL licensed libs can not be shipped with ASF projects but the apache link below [1] seems to indicate that ASF also believe that there are problems with LGPL too.

If InLong Agent does not ship the jar or if InLong Agent is an optional component that is not part of the main product, it might be ok - I think you'll need to talk to an expert.

You already list some Category X jars in https://github.com/apache/incubator-inlong/blob/master/DISCLAIMER-WIP but I think Aviator is also Category X.

[1] https://www.apache.org/legal/resolved.html
[2] https://github.com/killme2008/aviatorscript/blob/master/licenses.txt

### What you expected to happen

n/a

### How to reproduce

n/a

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@gosonzhang PTAL, thanks.

**Comment by gosonzhang** [comment]
@pjfanning, you're right!
