### ISSUE TITLE
[Bug][Audit] CommunicationsException occurred in unit tests

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#2468]
### What happened

![image](https://user-images.githubusercontent.com/18047329/153534560-bd296d5e-8c4a-4a54-beb8-968a2b0d374e.png)

### What you expected to happen

UT run successfully

### How to reproduce

run `mvn test` for audit

### InLong version

master

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
it's better to mock the UT about MySQL.

**Comment by dockerzhang** [comment]
![image](https://user-images.githubusercontent.com/18047329/158006685-ceb2cb27-d5c1-4d77-b5bd-a5f4b12cb3ef.png)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/incubator-inlong/pull/3085.
