### ISSUE TITLE
[Bug][Sort] Dependency conflict caused by maven-shade-plugin

### ISSUE THREAD

**Issue by KevinWen007** [apache/incubator-inlong#2476]
### What happened

1. Error 'cannot find symbol' will be occurred when executing `mvn clean install && mvn test`
2. kafka client dependency conflict as blow:
   
<img width="932" alt="wecom-temp-5998082f71df63b694866487616f4981" src="https://user-images.githubusercontent.com/89561791/153599489-e723db01-5c2e-4354-be39-c63d41214216.png">

### What you expected to happen

There should be no problem.

### How to reproduce

`mvn clean install` and `mvn clean install && mvn test` will occasionally triger the bugs.

### InLong version

1.0.0

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
the problem is caused by using hadoop-common dependancy from different repo
<img width="1590" alt="wecom-temp-c3faaa06229e4ae35e1021c4c7aee11f" src="https://user-images.githubusercontent.com/18047329/153700235-71728738-2341-4e2b-8fde-31d18f54bd6b.png">
