### ISSUE TITLE
[Bug][manager] get NumberFormatException when creating a new stream

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#2529]
### What happened

![image](https://user-images.githubusercontent.com/18047329/154260070-318fa68b-1954-4514-b309-85ef24a9e2e3.png)

### What you expected to happen

create a new stream

### How to reproduce

creating a new stream successfully

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I'll fix this bug.
