### ISSUE TITLE
[Bug][Manager] Wrong interface method parameter type

### ISSUE THREAD

**Issue by herywang** [apache/incubator-inlong#2597]
### What happened

# Description
There is an error method parameter type .
![image](https://user-images.githubusercontent.com/28130163/154787835-bf6427d6-0568-4939-9687-15a0524b7ccd.png)

# Use case
None

### What you expected to happen

mvn compile successful

### How to reproduce

https://github.com/apache/incubator-inlong/runs/5256772304?check_suite_focus=true

### Environment

github maven build environment

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Was solved in this PR: https://github.com/apache/incubator-inlong/pull/2581
