### ISSUE TITLE
[Improve][K8s] Improve InLong on Kubernetes

### ISSUE THREAD

**Issue by shink** [apache/incubator-inlong#2621]
### Description

Some work about k8s has been done, but there are still some areas for improvement.
For example, changing names, improving configuration and documentation, etc.

### Subtasks

- [x] #2510
- [x] #2622
- [x] #2631
- [x] #2632
- [x] #2640
- [x] #2643

### InLong Component

InLong Manager, InLong Dashboard, InLong Agent, InLong DataProxy, InLong SDK, InLong TubeMQ, InLong Sort, InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
all subtasks completed, close it.
