### ISSUE TITLE
[Bug][Manager]apache_inlong_manager.sql file execution exception

### ISSUE THREAD

**Issue by Greedyu** [apache/incubator-inlong#2638]
### What happened

https://inlong.apache.org/docs/next/modules/manager/quick_start . initialize database there is sql/apache_inlong_manager.sql. Throw an exception: ERROR 1364 (HY000) at line 316: Field 'mq_set_name' doesn't have a default value
![wecom-temp-4e67b3a8d022915f435c1d1470d6d9a8](https://user-images.githubusercontent.com/20356765/154970283-29a886d9-7eca-4ce7-8a8e-aa09480c9c31.png)

### What you expected to happen

The default value of the mq_set_name field should be null, otherwise the subsequently inserted instance should be assigned a value

### How to reproduce

execute sql script

### Environment

centos

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by this PR: https://github.com/apache/incubator-inlong/pull/2656
