### ISSUE TITLE
[Feature][Manager] Support Kafka source in Inong Stream

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#2653]
### Description

Support Kafka source in Inong Stream.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by herywang** [comment]
I will resolve this issue.
