### ISSUE TITLE
[Feature]fix the problem of common dependcy of agent

### ISSUE THREAD

**Issue by LvJiancheng** [apache/incubator-inlong#2675]
### Description

fix common dependency (common rely on agent) 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
this bug has not happened again, close it.

**Comment by LvJiancheng** [comment]
ok
