### ISSUE TITLE
[Bug][Manager] Field ext_params in table data_proxy_cluster not exits

### ISSUE THREAD

**Issue by liaorui** [apache/incubator-inlong#2699]
### What happened

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/2731242/155501522-ed82ef04-a61c-4f00-a5bc-7459830604c9.png">

### What you expected to happen

manager-web runs well

### How to reproduce

this problem is in the latest master code 

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Resolved in https://github.com/apache/incubator-inlong/pull/2708
