### ISSUE TITLE
[Bug][Manager] Inlong_group status ERROR

### ISSUE THREAD

**Issue by herywang** [apache/incubator-inlong#2700]
### What happened

# Looking this picture:
![image](https://user-images.githubusercontent.com/28130163/155512192-5b7410de-7dc5-4f62-8caf-6d47fdbbed4f.png)
-----------
![image](https://user-images.githubusercontent.com/28130163/155512279-c3732edb-c8eb-4c6d-8b1b-80c85d181814.png)
I guess there are some operation missed about updating inlong_group table `status` field in approve passed event. 

### What you expected to happen

Correct status.

### How to reproduce

In `联调环境`

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by other PR.
