### ISSUE TITLE
[Bug][DataProxy] Setting multiple topics for the same groupId doesn't work for Pulsar

### ISSUE THREAD

**Issue by pocozh** [apache/incubator-inlong#2719]
### What happened

For pulsar mq, setting multiple topics for the same groupId doesn't work

### What you expected to happen

Support multiple topics for pulsar mq

### How to reproduce

Setting multiple topics for pulsar mq

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
The original code works well, at the moment it looks like this commit is not necessary.
