### ISSUE TITLE
[Bug][Manager] data_source_cmd_config table not exit

### ISSUE THREAD

**Issue by herywang** [apache/incubator-inlong#2720]
### What happened

![image](https://user-images.githubusercontent.com/28130163/155681184-441d259b-7f9f-419d-a1ab-92fb52bbf8c2.png)

### What you expected to happen

None 

### How to reproduce

https://github.com/apache/incubator-inlong/issues/new?assignees=&labels=bug&template=bug-report.yml&title=%5BBug%5D

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Resolved by https://github.com/apache/incubator-inlong/pull/2708
