### ISSUE TITLE
[Bug]fail when delete a group

### ISSUE THREAD

**Issue by gong** [apache/incubator-inlong#2746]
### What happened

it will fail when I delete a group. Because code will check exist stream. 

### What you expected to happen

delete success

### How to reproduce

invoke  `api/inlong/manager/group/delete/{groupid}`

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
it does not happen again, close it.
