### ISSUE TITLE
[Bug][Manager] InlongGroupController update interface status problem  

### ISSUE THREAD

**Issue by Greedyu** [apache/incubator-inlong#2759]
### What happened

First create a group to be submitted.
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/20356765/155844035-48b47b8b-b973-4b51-90fe-c3ded366d75d.png">
Enter the page by clicking Details and click Next. An exception will occur：There was an error in the service...Please try again later! If there are still problems, please contact the administrator
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/20356765/155844088-13b03bda-06a8-4723-bd44-0457e9874b1f.png">

### What you expected to happen

There should be no exception

### How to reproduce

has been described earlier

### Environment

centos

### InLong version

master

### InLong Component

InLong Manager, InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/incubator-inlong/issues/3053
