### ISSUE TITLE
[Bug][Manager] Delete data grouping exception

### ISSUE THREAD

**Issue by Greedyu** [apache/incubator-inlong#2760]
### What happened

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/20356765/155844231-a60da7bf-7f55-498d-a984-0f738a7c9d3e.png">

### What you expected to happen

There should be no exception

### How to reproduce

Just delete an InlongGroup

### Environment

centos

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Was fixed in `UpdateGroupCompleteListener` class.
