### ISSUE TITLE
[Bug][Manager] The `middleware_type` of inlong_group table is "TUBE", even if choosing Pulsar as MQ while creating groupId

### ISSUE THREAD

**Issue by pocozh** [apache/incubator-inlong#2768]
### What happened

The `middleware_type` of inlong_group table is "TUBE", even if choosing Pulsar as MQ while creating groupId.

### What you expected to happen

The `middleware_type` of inlong_group table is "PULSAR" even if choosing Pulsar as MQ while creating groupId. 

### How to reproduce

-

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Already fixed by other PR.
