### ISSUE TITLE
[Bug][Dataproxy] Port conflict with pulsar port

### ISSUE THREAD

**Issue by herywang** [apache/incubator-inlong#2783]
### What happened

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/28130163/155948464-6c94230a-cc69-4275-8f1d-761c36051877.png">

pulsar port:
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/28130163/155948616-14c20728-0feb-4ae3-8d6f-6d7cbd7b0115.png">

### What you expected to happen

change inlong-dataporxy component port 

### How to reproduce

None

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
it's not a bug, you should configure different ports when deploying all modules on a machine.
