### ISSUE TITLE
[Feature] Replace MySQL with PostgreSQL

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#2784]
### Description

include inlong-manager、tubemq-manager、audit-store three modules, for license reason, we should replace MySQL with PostgreSQL in the following versions.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
Is anyone dealing with this now? If not, I want to contribute some code

**Comment by TszKitLo40** [comment]
> Is anyone dealing with this now? If not, I want to contribute some code
I think this issue has not been picked up, isn't it ? @dockerzhang

**Comment by dockerzhang** [comment]
@seedscoder I will fix this issue, you can have a review after PRs available.
