### ISSUE TITLE
[Bug] Manager website should not display port when adding agent job

### ISSUE THREAD

**Issue by EMsnap** [apache/incubator-inlong#2794]
### What happened

<img width="353" alt="wecom-temp-d9ab4eb9885e776ad00bd917bb1befc4" src="https://user-images.githubusercontent.com/26538404/156092495-9ac88529-9f33-4253-bb0c-1275b8789801.png">
Here, there's no use to add a port section since agent pull task from manager

### What you expected to happen

<img width="353" alt="wecom-temp-d9ab4eb9885e776ad00bd917bb1befc4" src="https://user-images.githubusercontent.com/26538404/156092495-9ac88529-9f33-4253-bb0c-1275b8789801.png">
no port here 

### How to reproduce

<img width="353" alt="wecom-temp-d9ab4eb9885e776ad00bd917bb1befc4" src="https://user-images.githubusercontent.com/26538404/156092495-9ac88529-9f33-4253-bb0c-1275b8789801.png">

### InLong version

0.12.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
the guild document should change too after this bug is fixed.

**Comment by leezng** [comment]
The manager needs to be modified together, otherwise the API will get error.
