### ISSUE TITLE
[Bug] Agent mysql connection should set allowPublicKeyRetrieval to true to support mysql 8.0

### ISSUE THREAD

**Issue by EMsnap** [apache/incubator-inlong#2826]
### What happened

[Bug] Agent mysql connection should set allowPublicKeyRetrieval to true to support mysql 8.0

### What you expected to happen

[Bug] Agent mysql connection should set allowPublicKeyRetrieval to true to support mysql 8.0

### How to reproduce

[Bug] Agent mysql connection should set allowPublicKeyRetrieval to true to support mysql 8.0

### InLong version

0.12.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
Is it necessary to set this parameter to true?

> https://mysqlconnector.net/connection-options/

```
 Note that AllowPublicKeyRetrieval=True could allow a malicious proxy to perform a MITM attack to get the plaintext password, so it is False by default and must be explicitly enabled.
```
