### ISSUE TITLE
[Feature] support inlong manager to use other plugin of Authorization

### ISSUE THREAD

**Issue by wardlican** [apache/incubator-inlong#2855]
### Description

support inlong manager to use other plugin of Authorization

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
completed by https://github.com/apache/incubator-inlong-website/pull/294, close it.
