### ISSUE TITLE
[Bug] Typo in manager achitecture on inlong website

### ISSUE THREAD

**Issue by EMsnap** [apache/incubator-inlong#2882]
### What happened

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/26538404/156585786-0cf3559b-cee6-4cb1-9b11-9e46ece47b59.png">
should be flow

### What you expected to happen

should be flow

### How to reproduce

should be flow

### InLong version

0.12.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
the image address is https://inlong.apache.org/docs/next/modules/manager/overview.
change to `good first issue`.

**Comment by seedscoder** [comment]
How to modify the text on the picture, PS?How to modify the text on the picture, PS?

**Comment by dockerzhang** [comment]
@seedscoder here we can redraw the picture using PPT or https://processon.com/
