### ISSUE TITLE
[Bug][Agent] ManagerFetcher throws exception when invoke the Gson.fromJson method

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#2883]
### What happened

The error log:

<img width="1148" alt="a9a56d7eb2ddc6053" src="https://user-images.githubusercontent.com/31994335/156602589-36a68bb1-d714-4866-955d-2dddb3e6ef50.png">

### What you expected to happen

No exception happens.

### How to reproduce

See the above log.

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I will fix this bug.
