### ISSUE TITLE
[Bug][Manager] Stream source was not deleted when calling delete operate

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#2888]
### What happened

Stream source was not deleted when calling delete operate.

### What you expected to happen

Should set is_deleted = source_id.

### How to reproduce

Just delete the source by id, you'll see the is_deleted field of this source still is 0. 

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I can fix this issue.
