### ISSUE TITLE
apache inlong FlinkSQL如何对接？[Question]

### ISSUE THREAD

**Issue by walkhan** [apache/incubator-inlong#2951]
### Question

1.数据通过apache inlong采集到kafka或者pulsar，如何采用flinkSQL对接？目前没有看地相关FlinkSQL内容？
2.从采集到Kafka或者Pulsar采用界面化配置即可？
3.看官网standalone也有集群，那么和依赖Flink的集群有啥区别？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
move to the discussion board,  close it.

detail at: https://github.com/apache/incubator-inlong/discussions/2952
