### ISSUE TITLE
[Feature][Sort] Add deploy command of sort-standalone

### ISSUE THREAD

**Issue by vernedeng** [apache/incubator-inlong#3011]
### Description

add start/stop commond of sort-standalone

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luchunliang** [comment]
The issue had been finished.
Fix #1889
