### ISSUE TITLE
[Improve] flink_bin variable in inlong-daemon script can be obtained values from FLINK_HOME

### ISSUE THREAD

**Issue by bigdata-page** [apache/incubator-inlong#3075]
### Description

when start or stop sort flink job，the find command can take a long time，if the flink_bin can be obtained values from FLINK_HOME，will save some time。

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@crancchen PTAL
