### ISSUE TITLE
[Bug][Sort] TubeClientException occurred in unit tests

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#3078]
### What happened

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/18047329/158001776-22004e25-adff-4269-b65f-20ef476a2968.png">

### What you expected to happen

runs without exception

### How to reproduce

https://github.com/apache/incubator-inlong/runs/5519194718?check_suite_focus=true
search `TubeClientException`.

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chantccc** [comment]
It's not a exception thrown, but a stack trace printed in log. So it's not a problem.
This UT case aims to test retrying to subscribe tube and fails finally .
