### ISSUE TITLE
[Bug][TubeMQ] An NPE was thrown when starting the Tube-Manager

### ISSUE THREAD

**Issue by bigdata-page** [apache/incubator-inlong#3079]
### What happened

When start tubemq-manager, the error is : org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException。

Reason analysis: the springboot 2.6.x modify the default strategy for matching request paths, reference [pathpattern-based-path-matching-strategy-for-spring-mvc](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#pathpattern-based-path-matching-strategy-for-spring-mvc).

temporary solution: add the properties: `spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER`

### What you expected to happen

the tubemq-manager service is started normally.

### How to reproduce

exec the command: ./bin/inlong-daemon start tubemanager

### Environment

linux

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bluewang** [comment]
already fixed
