### ISSUE TITLE
[Bug] Fix dataproxy UT bug, add mock of MetricRegister.

### ISSUE THREAD

**Issue by luchunliang** [apache/incubator-inlong#3080]
### What happened

Fix dataproxy UT bug, add mock of MetricRegister.

### What you expected to happen

dataproxy UT pass.

### How to reproduce

rebuild

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/incubator-inlong/pull/3081.
