### ISSUE TITLE
[Bug][Sort-Standalone] optimize the sort-standalone

### ISSUE THREAD

**Issue by vernedeng** [apache/incubator-inlong#3115]
### Description

Fix bugs in sort-standalone

- [x] #3116
- [x] #3117
- [x] #3121
- [x] #3122
- [x] #3173 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

- [ ]

**Comment by dockerzhang** [comment]
all sub-tasks completed, close it.
