### ISSUE TITLE
[Improve][InLong] Add a git hook to normalize commit messages

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#3167]
### Description

Out commit message should normalization, for example:

```
[INLONG-3160][Manager] Deleting stream source failed as the status was not allowed to delete
```

1. The first `[INLONG-3160]` indicates that this PR is used to solve Issue number `3168`.

3. The second `[Manager]` indicates that this PR belongs to the Manager module.

4. After a space, add your Commit message.

### InLong Component

Other for the not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MikeoPerfect** [comment]
m

**Comment by dockerzhang** [comment]
@MikeoPerfect this issue was assigned to you, please fix it recently, thanks a lot.

**Comment by MikeoPerfect** [comment]
> @MikeoPerfect this issue was assigned to you, please fix it recently, thanks a lot.

sure, I will do it

**Comment by MikeoPerfect** [comment]
> @MikeoPerfect this issue was assigned to you, please fix it recently, thanks a lot.

sure, I will do it

**Comment by dockerzhang** [comment]
@MikeoPerfect do you still work on this issue?

**Comment by MikeoPerfect** [comment]
@dockerzhang  suspend，someone else may have a try, I will follow it

**Comment by ciscozhou** [comment]
https://github.com/apache/incubator-inlong/pull/3571 was not work, I'll solve later.
