### ISSUE TITLE
[Improve]add check param for manager-client

### ISSUE THREAD

**Issue by gong** [apache/incubator-inlong#3178]
### Description

add check param for manager-client

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/incubator-inlong/pull/3177
