### ISSUE TITLE
[Bug]After approval, the new pulsar Data Streams Group middleware becomes TUBE

### ISSUE THREAD

**Issue by xuesongxs** [apache/incubator-inlong#3224]
### What happened

After approval, the new pulsar Data Streams Group middleware becomes TUBE.
![image](https://user-images.githubusercontent.com/54351417/158969024-6ad72346-e3b7-44d1-9b3a-b7bfbcb9453a.png)

### What you expected to happen

Pulsar Data Streams Group Display Pulsar detail, not tube.

### How to reproduce

1、Create Pulsar Data Streams Group
2、Approve the Pulsar Data Streams Group
3、View Pulsar Data Streams Group details

### Environment

Centos 7.2

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@leezng PTAL

**Comment by leezng** [comment]
Sorry, we have not reproduced the bug, please try to deploy with the latest code.
