### ISSUE TITLE
[Improve][Agent] Get local IP when IP in config is not present 

### ISSUE THREAD

**Issue by EMsnap** [apache/incubator-inlong#3266]
### Description

[Improve] Agent get local ip when ip in config is not present

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
@[wilburjiang0](https://github.com/wilburjiang0) Thanks for your contribution.
Please add some comments on this issue, then I can assign it to you.

**Comment by wilburjiang0** [comment]
please assign this issue to me, thx.
