### ISSUE TITLE
[Bug][Agent] Report job result rather than task result

### ISSUE THREAD

**Issue by EMsnap** [apache/incubator-inlong#3299]
### What happened

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/26538404/159454124-66d34640-14b9-4238-9780-d731396178e3.png">

Kafka job has multiple task so taskid is not suitable in commandentity

### What you expected to happen

Kafka job has multiple task so taskid is not suitable in commandentity

### How to reproduce

Kafka job has multiple task so taskid is not suitable in commandentity

### InLong version

0.12.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/incubator-inlong/pull/3303/files
