### ISSUE TITLE
[Improve][Manager] Remove deprecated classes and tables

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#3301]
### Description

Remove deprecated classes and tables, include inlong_stream_ext, source_field, and source_db.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I can resolve this issue.
