### ISSUE TITLE
[Bug][Manager] Should update status when agent result was failed

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#3339]
### What happened

Should update status when agent result was failed.

### What you expected to happen

When agent result was failed, should update task status to FAILED.

### How to reproduce

See the code in `AgentServiceImpl#updateCommandEntity()`.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
Pls assign it to me.
