### ISSUE TITLE
[Bug][Manager] Fix database error when saving sink field

### ISSUE THREAD

**Issue by yunqingmoswu** [apache/incubator-inlong#3398]
### What happened

Database error when saving sink field if the format field is not configured.

### What you expected to happen

Saving sink field success even if the format field is not configured.

### How to reproduce

Does not configure the format field when saving the sink field.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Duplicated with https://github.com/apache/incubator-inlong/pull/3401
