### ISSUE TITLE
[Agent] Sort out the LICENSEs of the third-party components of inlong-agent

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#3437]
### Description

The parent issue is: #3422

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pocozh** [comment]
resolved this issue

**Comment by gosonzhang** [comment]
@pocozh thanks!
