### ISSUE TITLE
[Audit] Sort out the LICENSEs of the third-party components of inlong-audit

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#3440]
### Description

The parent issue is: #3422

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by doleyzi** [comment]
I solve it

**Comment by gosonzhang** [comment]
@doleyzi thanks!
