### ISSUE TITLE
[Bug] upgrade to jackson-databind 2.12.6.1 (due to cve)

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-inlong#3504]
### What happened

dependabot alert

https://github.com/advisories/GHSA-57j2-w4cx-62h2

only jackson-databind has a 2.12.6.1 release - other jackson jars should be upgraded to 2.12.6

### What you expected to happen

n/a

### How to reproduce

n/a

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
Did anyone else start dealing with it? If not, I'll upgrade this component

**Comment by pjfanning** [comment]
I added https://github.com/apache/incubator-inlong/pull/3570
