### ISSUE TITLE
[Sort-Flink] Remove lzo-core dependency

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#3523]
### Description

![image](https://user-images.githubusercontent.com/14038849/161379745-58643078-d910-44b9-bc0c-65ddd6726bf7.png)

Since lzo-core belongs to the GPL type of protocol authorization, it does not meet Apache's protocol requirements for third-party dependent packages. It must be removed and adjust the corresponding code logic at the same time.

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chantccc** [comment]
Assign to me please
