### ISSUE TITLE
[Bug][Agent] Failed to send the create job request(POST /config/jobs)

### ISSUE THREAD

**Issue by bigdata-page** [apache/incubator-inlong#3594]
### What happened

When run the example command of [agent file type job docs](https://inlong.apache.org/zh-CN/docs/next/modules/agent/file), the request failed: {"code":-1,"message":"null value for key job.sourceType"}。

### What you expected to happen

The reqeust success.

### How to reproduce

Run the example command of [agent file type job docs](https://inlong.apache.org/zh-CN/docs/next/modules/agent/file)

### Environment

Ubuntu/Java8

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
please try the latest version
