### ISSUE TITLE
[Feature][InLong] Tidy up dependencies for all modules

### ISSUE THREAD

**Issue by baomingyu** [apache/incubator-inlong#3622]
### Description

Tidy up dependencies for all modules.

### Use case

Tidy up dependencies for all modules.

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pjfanning** [comment]
@baomingyu is this related to https://github.com/apache/incubator-inlong/issues/3284
