### ISSUE TITLE
[Improve][InLong] Fix the Javadoc check style problems for all modules

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#3635]
### Description

Search the log in https://github.com/apache/incubator-inlong/runs/5983318801?check_suite_focus=true, include:
- InvalidJavadocPosition
- SummaryJavadoc
- SingleLineJavadoc

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
@haibo-duan Please reply this comment, and then I can assign this issue to you, thanks.
