### ISSUE TITLE
[Improve][InLong] Fix the warning logs during the build

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#3636]
### Description

Search `Warning` in https://github.com/apache/incubator-inlong/runs/5983318801?check_suite_focus=true

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haibo-duan** [comment]
please assign it to me. thanks.
