### ISSUE TITLE
[Feature][Manager] Support complex data type distribution for hive-sink

### ISSUE THREAD

**Issue by LvJiancheng** [apache/incubator-inlong#3698]
### Description

Support complex data type distribution for hive-sink ;include Map;Array;Struct

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Same as #4137.
