### ISSUE TITLE
[BUG][Manager] Fix the Flink savepoint configuration

### ISSUE THREAD

**Issue by LvJiancheng** [apache/incubator-inlong#3745]
### What happened

fix flink savepoint configuration

### What you expected to happen

fix flink savepoint configuration

### How to reproduce

fix flink savepoint configuration

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/incubator-inlong/pull/3754
