### ISSUE TITLE
[Imporve][Manager] Add  configuration item of metrics.audit.proxy.hosts

### ISSUE THREAD

**Issue by LvJiancheng** [apache/incubator-inlong#3751]
### Description

Add  configuration item of metrics.audit.proxy.hosts

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Duplicated with #3753
