### ISSUE TITLE
[Bug][UT] TubeMQ MessageFetchManagerTest failed 

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#3763]
### What happened

![企业微信截图_16501058581779](https://user-images.githubusercontent.com/18047329/163673934-98c32b90-f925-4571-abf8-180e8472b581.png)

### What you expected to happen

UT passed

### How to reproduce

see the CI workflow.

### InLong version

1.1.0

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Thanks, @dockerzhang , a rather strange problem, this piece of UT has not been modified for a long time, I added "@PowerMockIgnore("javax.management.*")" in front of the UT to solve these failures, but where did it come from needs further analysis
