### ISSUE TITLE
[Feature][Sort] Fix meta field sync error

### ISSUE THREAD

**Issue by yunqingmoswu** [apache/incubator-inlong#3815]
### Description

Fix meta field sync error

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Same as https://github.com/apache/incubator-inlong/pull/3820.
