### ISSUE TITLE
[Improve][Manager] Update status enum for group, stream, source, and sink

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#3879]
### Description

Update status enum for group, stream, source, and sink.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I can refactor this issue.
