### ISSUE TITLE
[Bug][Manager]

### ISSUE THREAD

**Issue by Greedyu** [apache/incubator-inlong#3888]
### What happened

The batchSaveAll() method submits the form interface exception, and there is no sink_name to fill in the form. But the database sets the field to be non-null
![image](https://user-images.githubusercontent.com/20356765/164685835-645f618c-ab8b-45d3-95db-7727d3b54b37.png)

### What you expected to happen

No Errors

### How to reproduce

Create a hive sink

### Environment

centos

### InLong version

master

### InLong Component

InLong Manager, InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Already resolved.
