### ISSUE TITLE
[Improve][Manager] Add primary key in Kafka source 

### ISSUE THREAD

**Issue by chestnut-c** [apache/incubator-inlong#3921]
### Description

Add primary key in Kafka source 

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kipshi** [comment]
kafka source not needed ,kafka sink is needed;
