### ISSUE TITLE
[Feature][Manager] Fetch source failed and update task status through heartbeat

### ISSUE THREAD

**Issue by LvJiancheng** [apache/incubator-inlong#3922]
### Description

fetch source failed status through heartbeat and update task status through heartbeat

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
it's solved, close it.
