### ISSUE TITLE
[Improve][Manager] Implement the APIs of cluster management

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#3946]
### Description

Implement the APIs of cluster management.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
I will deal with this problem.
