### ISSUE TITLE
[Feature] Add support for Dependabot

### ISSUE THREAD

**Issue by shink** [apache/incubator-inlong#3974]
### Description

Add support for [Dependabot](https://docs.github.com/en/enterprise-server@3.4/code-security/dependabot)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GanfengTan** [comment]
link [INLONG-3956][Sort] Add Hive connector to support CDC (https://github.com/apache/incubator-inlong/pull/3963)
