### ISSUE TITLE
[Bug][Sort] Change the restriction of Hive catalogName from not nullable to nullable

### ISSUE THREAD

**Issue by GanfengTan** [apache/incubator-inlong#4035]
### What happened

flink hive connector parame of default is hive

### What you expected to happen

only one hive cluster, unnecessary parameter

### How to reproduce

hive load

### Environment

macOS 10.15.7

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by #4036
