### ISSUE TITLE
[Improve][Manager] Remove zone tag field of inlong cluster table

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#4052]
### Description

Remove zone tag field of inlong cluster table.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
Please assign it to me.
