### ISSUE TITLE
[Improve][Manager] Add some fields for stream_source and stream_sink

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#4084]
### Description

For the stream_source table, change the `server_id` field to the `data_node_name`:

```
`data_node_name` varchar(128) DEFAULT NULL COMMENT 'Node name, which links to data_node table',
```

For the stream_sink table, add the flowing fields before the `ext_params` field.

```
`inlong_cluster_name` varchar(128) DEFAULT NULL COMMENT 'Cluster name, which links to inlong_cluster table',
`data_node_name` varchar(128) DEFAULT NULL COMMENT 'Node name, which links to data_node table',
`sort_task_name` varchar(512) DEFAULT NULL COMMENT 'Sort task name or task ID',
`sort_consumer_group` varchar(512) DEFAULT NULL COMMENT 'Consumer group name for Sort task',
```

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
I will deal with this problem
