### ISSUE TITLE
[Feature][Dashboard] Create ClickHouse sink need to fill more params

### ISSUE THREAD

**Issue by lucaspeng12138** [apache/incubator-inlong#4089]
### Description

ClickHouse Create operation has more inputs than given. Such as creating table, Engine is must be given. And user may also want to input ORDER BY, PRIMARY KEY and so on. In column information, user may input DefaultType, CODEC and TTL.

According to: https://clickhouse.com/docs/zh/sql-reference/statements/create/table

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/100204617/167099334-b3faaef3-c511-4b8b-a40b-e67f2e182343.png">

### Use case

When creating a table on clickhouse, can input Engine, ORDER BY, PRIMARY KEY. In creating column can input DefaultType, CODEC and TTL.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
@leezng please cc.

**Comment by leezng** [comment]
Close by #4285
