### ISSUE TITLE
[Improve][Manager] Change the keyWord to keyword in query params

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#4120]
### Description

Change the keyWord to keyword in query params.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I want to resolve this issue, please assign it to me.

**Comment by healchow** [comment]
@ciscozhou thanks for your contribution.
