### ISSUE TITLE
[Bug][K8s] HTTP error appears on the login dashboard when deploying InLong using helm

### ISSUE THREAD

**Issue by eason0413** [apache/incubator-inlong#4144]
### What happened

HTTP error appears on the login inlog dashboard when deployed InLong by helm in kubernetes
![inlong-dashboard-login-httperror](https://user-images.githubusercontent.com/53069756/167535320-37c29786-55e8-4496-b06a-89d5767c037f.png)

### What you expected to happen

I  expect  to login to inlong dashboard successfully.

### How to reproduce

when login to inlong  dashboard, I see logs of inlong-dashboard-0, as follows,
2022/05/10 00:51:44 [error] 8#8: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 10.244.2.0, server: _, request: "POST /api/inlong/manager/anno/login HTTP/1.1", upstream: "http://10.109.66.41:8089/api/inlong/manager/anno/login", host: "192.168.227.133:30081", referrer: "http://192.168.227.133:30081/"
10.244.2.0 - - [10/May/2022:00:51:44 +0000] "POST /api/inlong/manager/anno/login HTTP/1.1" 502 559 "http://192.168.227.133:30081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" "-"
It shows inlong-dashboard can not access to inlong-manager,  so far, maybe the  API config of dashboard with inlong-manager it not ok，check the API config of dashboard with inlong-manager and fix it in order to solve the problem.

### Environment

helm            version: v3.8.0
kubernetes version: v1.16.0
helm chart: https://github.com/apache/incubator-inlong/tree/master/docker/kubernetes
Installation guide: https://inlong.apache.org/zh-CN/docs/deployment/k8s/

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shink** [comment]
@eason0413 Thank you for your attention. Somewhere wrong in `dashboard-statefulset.yml`. Changing `tubemqManager` to `manager` can fix this bug.
![image](https://user-images.githubusercontent.com/49934421/167541408-1c5f1395-2478-4ac6-bc76-2c0c208e3f29.png)
