### ISSUE TITLE
[Improve][Manager] Remove fastjson dependency

### ISSUE THREAD

**Issue by leosanqing** [apache/incubator-inlong#4239]
### Description

1. remove fastjson dependency

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Resolved by #4242
