### ISSUE TITLE
[Improve][Manager] Optimize client http request

### ISSUE THREAD

**Issue by leosanqing** [apache/incubator-inlong#4381]
### Description

1. Optimize client http request，Simplified method
2. use Jackson instead of gson
3. add some junit tests

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@leosanqing do you still work on this issue?

**Comment by leosanqing** [comment]
> @leosanqing do you still work on this issue?

Yes, I have completed the development, but when merging the code, I found that some util classes disappeared, waiting for healchow to complete the new util class

@healchow
