### ISSUE TITLE
[Bug][Sort] Excluse or remove the mysql:mysql-connector-java:jar:8.0.21 package

### ISSUE THREAD

**Issue by gosonzhang** [apache/incubator-inlong#4385]
### What happened

The parent issue is: https://github.com/apache/incubator-inlong/issues/4276
![image](https://user-images.githubusercontent.com/14038849/170408977-b91ea3b1-e0f6-4ba0-bb0e-8976077bc6e4.png)

![image](https://user-images.githubusercontent.com/14038849/170409022-30603d11-00a0-4baf-88bf-f76d7561d4e5.png)

### What you expected to happen

compile

### How to reproduce

compile

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GanfengTan** [comment]
I am willing to submit a PR.

**Comment by gosonzhang** [comment]
@GanfengTan, thanks!
