### ISSUE TITLE
[Improve][docker-compose] audit container exited not running

### ISSUE THREAD

**Issue by jinze1107** [apache/incubator-inlong#4416]
### Description

docker-compose up -d run inlong ，audit container exited not running

audit container  log
➜  docker-compose git:(master) ✗ docker logs -f audit
bin/audit-docker.sh: 31: [: pulsar: unexpected operator
bin/audit-docker.sh: 36: [: pulsar: unexpected operator
bin/audit-docker.sh: 43: Syntax error: "(" unexpected (expecting "then")
bin/audit-docker.sh: 31: [: pulsar: unexpected operator
bin/audit-docker.sh: 36: [: pulsar: unexpected operator
bin/audit-docker.sh: 43: Syntax error: "(" unexpected (expecting "then")

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
I test the latest image, it works for me. you can try the `inlong/audit:latest` to verify again.
