### ISSUE TITLE
[Improve][InLong] master  maven build FAILURE

### ISSUE THREAD

**Issue by jinze1107** [apache/incubator-inlong#4418]
### Description

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.713 s
[INFO] Finished at: 2022-05-28T23:50:43+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (default) on project inlong: Too many files with unapproved license: 170 See RAT report in: /Users/jinze/IdeaProjects/incubator-inlong/target/rat.txt -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
you can check the content `/Users/jinze/IdeaProjects/incubator-inlong/target/rat.txt` to find which file has no license. I think it's probably the file newly added by yourself.

**Comment by dockerzhang** [comment]
please do not compile and run docker-compose in the same directory, it will generate some files without a license.
