### ISSUE TITLE
[Improve][Manager] Remove the ClusterBean class

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#4602]
### Description

Remove the ClusterBean class, because it was not needed anymore.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
ok
