### ISSUE TITLE
[Improve][Sort] Package Pulsar and Hive connectors to the same file

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#4624]
### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GanfengTan** [comment]
I am willing to submit a PR!
