### ISSUE TITLE
[Improve][Manager] Abstract operations on sink configuration to reduce repetitive cod 

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#4632]
### Description

Abstract operations on sink configuration to reduce repetitive code.

Referring to the `AbstractSourceOperation`, suggested creating a new abstract class and naming it `AbstractSinkOperator`.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
Please assign this issue to me, thx.

**Comment by healchow** [comment]
Ok, assigned.

**Comment by healchow** [comment]
> Please assign this issue to me, thx.
Assigned. Thanks for your contribution.
