### ISSUE TITLE
[INLONG-52] How to minimize the repeated message reception?

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#651]
<p>At present, TubeMQ does not perform data deduplication processing. Although distributed message middleware is difficult to achieve message duplication, how to do it can reduce as many duplicate messages received by each broker as possible without complex and heavy processing flow?</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-52">[INLONG-52]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
Closed for inactive for a long time

if needed, please reopened it
