### ISSUE TITLE
[INLONG-109] Optimize RPC

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#708]
<p>Remarks: I originally wanted to put the improvement items on cwiki to create an RFC for discussion. I found that I could not create it during the operation. I am not sure what the reason is. so create it on Jira first, then discuss, and then implement it.</p>

<p> </p>

<p>To summarize the recent analysis of the implementation of TubeMQ RPC, I think we need to adjust the following content of TubeMQ RPC to make the system more powerful:</p>

<p>1. The header of each RPC packet should consist of the length of the entire packet, not the number of multiple lists. It can be used to identify illegal packets and allocate memory resources in advance;</p>

<p>2. The error code and error information should be carried in the exception messages, instead of the original exception classes;</p>

<p>3. The structure of the response message of this method needs to be improved, the success field should be deleted, and errors should be distinguished by unique error codes. Use clear error codes to clearly mark specific error details so that SDK users can get the exact cause of the error and find clear error handling suggestions based on the documentation;</p>

<p>4. Each method in RPC should carry version information, so that different versions can correspond to different decoding schemes</p>

<p>5. If the subsequent RPC still uses PB for coding and decoding, you need to use maven-shade-plugin to cover PB and Netty. Otherwise, the jar package released can easily form a version conflict with the corresponding dependency package of the business</p>

<p> </p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-109">[INLONG-109]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
Closed for inactive for a long time

if needed, please reopened it
