### ISSUE TITLE
[INLONG-112] Enhance the system's ability to sense consumption status

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#711]
<p>At present, consumption does not consider consumers' consumption capacity and the current data backlog of partitions at all, which is not very friendly to flexible management systems and needs to be adjusted.</p>

<p>1. Support the statistics and reports of consumer consumption speed: the consumption speed of each consumer allowed by the system can be counted, so that the consumption status of each consumer can be clearly understood;</p>

<p>2. Master supports dynamic adjustment of partition allocation strategy based on user consumption speed, data production speed and data backlog, so that the fastest consumer consumes the partition with the largest data backlog</p>

<p>3. Master supports data statistics of consumer groups.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-112">[INLONG-112]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
Closed for inactive for a long time

if needed, please reopened it
