### ISSUE TITLE
[INLONG-114] Support consumers to adjust consumption targets without restarting

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#713]
<p>Users have reported a requirement that when the system uses TubeMQ, it will frequently modify the consumption topics or filter items. Can the system increase the consumption theme or filter items without restarting? it is very good for the business experience if If this function completed</p>

<p>1. The consumer only needs to fill in the target server, consumer group, user name, and password to consume directly; during the consumption process, consumers are allowed to adjust the consumption range, such as increasing and decreasing Topic, increasing and decreasing filtering tid, without restarting the customer Terminal program</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-114">[INLONG-114]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
