### ISSUE TITLE
[INLONG-129] Join "Open Source Promotion Plan - Summer 2020"

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#728]
<p>"Open Source Promotion Plan - Summer 2020" is Sponsored by Institute of software Chinese Academy of Sciences.</p>

<p>Some projects like Apache APISIX\Apache DolphinSchedule\Apache Pulsar\Apache ShardingSphere\Apache SkyWalking have joined this plan to attract more  outstanding students to participate in.</p>

<p>Plan Link:<a href="https://isrc.iscas.ac.cn/summer2020/#/index" class="external-link" rel="nofollow">https://isrc.iscas.ac.cn/summer2020/#/index</a></p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-129">[INLONG-129]</a> created by pierre94</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
