### ISSUE TITLE
[INLONG-151] Related compatible revision tracking

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#750]
<p>This Issue mainly tracks the adjustment requirements that need to be followed by compatibility-related changes, and is modified when appropriate to facilitate subsequent version optimization</p>

<p>NO.     ISSUE-ID     Conents<br/>
  1.     <a href="https://issues.apache.org/jira/browse/INLONG-140" title="Remove the SSD auxiliary consumption function" class="issue-link" data-issue-key="INLONG-140"><del>TUBEMQ-140</del></a>     the ssdStoreId field in pb message definition, BdbGroupFlowCtrlEntity class definition</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-151">[INLONG-151]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
