### ISSUE TITLE
[INLONG-191] New user mail list for TubeMQ users

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#790]
<p>There should be a user mail list. </p>

<p> </p>

<p>User who looking for document, guide or whatever, None development things. </p>

<p>Should find help and guide from the user mail list.</p>

<p> </p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-191">[INLONG-191]</a> created by netroby</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
