### ISSUE TITLE
[INLONG-305] Shade some common dependency used by tubemq-core

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#904]
<p>Currently, tubemq-core contains some common dependency such as protobuf, nutty and gson. include these dependencies without shading may cause the some class conflict because use code maybe wants to use a different versions. </p>

<p>In this issue, we propose to shade these dependencies <tt>protobuf</tt>, <tt>netty</tt>, and <tt>gson.</tt></p>

<p><tt>After this issue, the dependencies of }}{{protobuf</tt>, <tt>netty</tt> and <tt>gson</tt> can't be used by users directly, they need to add dependency themself if needed.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-305">[INLONG-305]</a> created by klion26</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
