### ISSUE TITLE
[INLONG-310] Upgrade WebAPI protocol: HTTP/1.1 => HTTP/2

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#909]
<p>THIS IS AN OPTIONAL TASK.<br/>
HTTP/2 could bring more intelligent control on Frames-based data submission (no longer a big form-data or alike), Interactive data exchange (Multiplexing/ServerPush mechanism), API QoS (Stream Prioritization), while current HTTP/1.1 could fulfill basic requirement of WebAPI.<br/>
So it brings bigger possibility to WebAPI, but it may not be bright spot improvement for now (or maybe some day <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<p>It's nice to discuss about it, and just implement it if this upgrade itself is straight-forward based on Jetty 9.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-310">[INLONG-310]</a> created by hystericalhell</i>

**Comment by gosonzhang** [comment]
Closed for inactive for a long time

if needed, please reopened it
