### ISSUE TITLE
[INLONG-313]  Broker heartbeat performance issues

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#912]
<p>Broker heartbeat performance issues</p>

<p>At present, Broker needs to report heartbeats regularly. In the case of large batch requests, when the CPU performance of the client and server is very high, the heartbeat report is not timely, and there is a high probability that the heartbeat report fails, causing the client to disconnect.<br/>
At the optimization point, the data packet request of the client can be regarded as the heartbeat data.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-313">[INLONG-313]</a> created by charleli</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
