### ISSUE TITLE
[INLONG-324] Consumer Models Init

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#923]
<p>Init Consumer models such as Topic、Partition、Broker、Fetcher </p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-324">[INLONG-324]</a> created by tangcunzhou</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
