### ISSUE TITLE
[INLONG-340] Add streamlined content metadata  API

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#937]
<p>At present, the content returned by the API provided by Master is very detailed, but in some scenarios, so much content is not required, for example, when  we check the deployment scope of a topic,  the configuration relationship between the topic and broker is required. so we need to add some simplified metadata information query API</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-340">[INLONG-340]</a> created by gosonzhang</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
