### ISSUE TITLE
[INLONG-372] Is there any strategy to ensure consumer start up smoothly

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#967]
<p>Nowadays I have encounter a problem when start up tube consumer from failover client，</p>

<p>by telling me the inconsistent session key I configured. </p>

<p><span class="image-wrap" style=""><img src="https://issues.apache.org/jira/secure/attachment/13013303/13013303_89bd93bb-fbb0-4d10-ad00-cbdbb0728894.png" height="109" width="1463" style="border: 0px solid black" /></span></p>

<p>After searching around, this may caused by the zombie consumer process which does not exit successfully from last session under the same consume group.</p>

<p>My question is: are there any solutions for user-friendly start up from unexpected failover.</p>

<p> </p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-372">[INLONG-372]</a> created by dashuye4</i>

**Comment by gosonzhang** [comment]
Closed due to long periods of inactivity

Please reopen it if needed
